version: '3.8'

services:
  easycommit:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      TRAIN_ON_START: "true"
    volumes:
      - ./output/easycommit_model:/app/output/easycommit_model
      - ./data/urls-github.json:/app/urls-github.json
      - ./training_log.csv:/app/training_log.csv
